enableTelemetry: false

nodeLinker: node-modules

packageExtensions:
  typedoc@*:
    peerDependencies:
      typedoc-plugin-markdown: '*'
      typedoc-plugin-no-inherit: '*'

preferInteractive: true
